spring:
  application:
    name: bank-ease-user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_ease_db
    username: bank_ease_user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        default_schema: bank_ease_schema
    hibernate:
      ddl-auto: none
  security:
    user:
      name: admin
      password: <PASSWORD_PLACEHOLDER>

server:
  port: 8080
